command:
  - "uvicorn"
  - "server.app:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "$DATABRICKS_APP_PORT"

env:
  - name: APP_TITLE
    value: "Vibe Coding Workshop"
  - name: PARTNER_NAME
    value: ""
  - name: ENV
    value: "production"
  - name: PROJECTS_BASE_DIR
    value: "./projects"
  - name: PYTHONPATH
    value: "./packages"
  - name: ENABLED_SKILLS
    value: "agent-bricks,aibi-dashboards,asset-bundles,databricks-app-apx,databricks-app-python,databricks-config,databricks-docs,databricks-jobs,databricks-python-sdk,databricks-unity-catalog,mlflow-evaluation,spark-declarative-pipelines,synthetic-data-generation,unstructured-pdf-generation"
  - name: SKILLS_ONLY_MODE
    value: "false"
  - name: LAKEBASE_INSTANCE_NAME
    value: "daveok"
  - name: LAKEBASE_DATABASE_NAME
    value: "databricks_postgres"
  - name: LLM_PROVIDER
    value: "DATABRICKS"
  - name: DATABRICKS_MODEL
    value: "databricks-meta-llama-3-3-70b-instruct"
  - name: DATABRICKS_MODEL_MINI
    value: "databricks-gemini-3-flash"
  - name: CLAUDE_CODE_STREAM_CLOSE_TIMEOUT
    value: "3600000"
  - name: DATABRICKS_CLAUDE_MODEL
    value: "databricks-claude-sonnet-4-5"
  - name: CLAUDE_API_TOKEN
    valueFrom: claude-pat
  - name: AUTO_GRANT_PERMISSIONS_TO
    value: "account users"
