command:
  - "node"
  - "dist/index.js"

env:
  - name: ENV
    value: "production"
  - name: PROJECTS_BASE_DIR
    value: "./projects"

  # Skills configuration
  - name: ENABLED_SKILLS
    value: "agent-bricks,aibi-dashboards,asset-bundles,databricks-app-apx,databricks-app-python,databricks-config,databricks-docs,databricks-jobs,databricks-python-sdk,databricks-unity-catalog,mlflow-evaluation,spark-declarative-pipelines,synthetic-data-generation,unstructured-pdf-generation"
  - name: SKILLS_ONLY_MODE
    value: "false"

  # Database (Lakebase)
  - name: LAKEBASE_INSTANCE_NAME
    value: "builder-app-db"
  - name: LAKEBASE_DATABASE_NAME
    value: "databricks_postgres"

  # Claude SDK settings
  - name: CLAUDE_CODE_STREAM_CLOSE_TIMEOUT
    value: "3600000"

  # Databricks Foundation Model API for Claude
  - name: DATABRICKS_CLAUDE_MODEL
    value: "databricks-claude-sonnet-4"

  # Databricks workspace URL
  - name: DATABRICKS_WORKSPACE_URL
    value: "https://adb-984752964297111.11.azuredatabricks.net"
